### ISSUE TITLE
SVG Dimensions are incorrect

### ISSUE THREAD

**Issue by Red3Tango** [PiCode9560/Godot-Prototype-Texture#1]
The SVG files are set to 512mm (1935.1182px) and not pixels.

This makes Godot import them at the full 1935x1935 pixels instead of 512x512 making the cached texture be 10MiB instead of 760KiB (a drastic difference).

**Comment by PiCode9560** [comment]
Fixed, thanks!

**Comment by Red3Tango** [comment]
Resolved 4a0a2c76743e77606e2c31da904eeababef7450d
